import fs from 'node:fs';
import path from 'node:path';
import { Question, isMultipleChoice } from '../interfaces';
import { createLogger } from '../utils/logger';

const log = createLogger('QuestionService');

/**
 * Loads and serves the static question bank from data/questions.json.
 *
 * Questions live in a JSON file (generated by scripts/generate-questions.ts),
 * NOT in the database, so the bank can be versioned and expanded easily. The
 * database only references question ids.
 */
class QuestionService {
  private questions: Question[] = [];
  private byId = new Map<number, Question>();
  private loaded = false;

  /** Candidate locations for questions.json (dev + compiled + override). */
  private candidatePaths(): string[] {
    const paths: string[] = [];
    if (process.env.QUESTIONS_PATH) paths.push(process.env.QUESTIONS_PATH);
    paths.push(path.join(__dirname, '..', 'data', 'questions.json'));
    paths.push(path.join(process.cwd(), 'dist', 'data', 'questions.json'));
    paths.push(path.join(process.cwd(), 'src', 'data', 'questions.json'));
    return paths;
  }

  /** Loads (and validates) the question bank. Safe to call multiple times. */
  load(): void {
    if (this.loaded) return;

    const file = this.candidatePaths().find((p) => fs.existsSync(p));
    if (!file) {
      throw new Error(
        '[QuestionService] questions.json not found. Run "npm run generate:questions".',
      );
    }

    const raw = fs.readFileSync(file, 'utf-8');
    const parsed = JSON.parse(raw) as Question[];

    const valid: Question[] = [];
    for (const q of parsed) {
      if (!this.isValid(q)) {
        log.warn(`Skipping invalid question (id=${(q as Question)?.id ?? '?'}).`);
        continue;
      }
      valid.push(q);
      this.byId.set(q.id, q);
    }

    this.questions = valid;
    this.loaded = true;
    log.info(`Loaded ${valid.length} questions from ${file}.`);
  }

  private isValid(q: Question): boolean {
    if (!q || typeof q.id !== 'number' || typeof q.question !== 'string') return false;
    if (typeof q.answer !== 'string' || q.answer.length === 0) return false;
    if (q.type === 'multiple_choice') {
      return (
        Array.isArray(q.options) &&
        q.options.length >= 2 &&
        q.options.includes(q.answer)
      );
    }
    return q.type === 'text_input';
  }

  /** Total number of questions in the bank. */
  get size(): number {
    this.ensureLoaded();
    return this.questions.length;
  }

  /** Returns a question by id, or null if it does not exist. */
  getById(id: number): Question | null {
    this.ensureLoaded();
    return this.byId.get(id) ?? null;
  }

  /** Resolves a list of ids into questions, dropping unknown ids. */
  getManyByIds(ids: number[]): Question[] {
    this.ensureLoaded();
    return ids
      .map((id) => this.byId.get(id))
      .filter((q): q is Question => q !== undefined);
  }

  /**
   * Picks `count` distinct random question ids. Deterministic-friendly: callers
   * may pass a seed-derived RNG if reproducibility is ever required.
   */
  pickRandomIds(count: number): number[] {
    this.ensureLoaded();
    const pool = this.questions.map((q) => q.id);
    // Fisher–Yates partial shuffle.
    for (let i = pool.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [pool[i], pool[j]] = [pool[j], pool[i]];
    }
    return pool.slice(0, Math.min(count, pool.length));
  }

  /**
   * For multiple-choice questions, returns options in a stable (already shuffled
   * at generation time) order. Helper kept for clarity at call sites.
   */
  getOptions(question: Question): string[] {
    return isMultipleChoice(question) ? question.options : [];
  }

  private ensureLoaded(): void {
    if (!this.loaded) this.load();
  }
}

export const questionService = new QuestionService();
