/**
 * Database seed.
 *
 * The question bank itself lives in data/questions.json (generated by
 * scripts/generate-questions.ts), so seeding only needs to make sure today's
 * DailyQuestion set exists, so /daily works immediately after a fresh install.
 *
 * Run with:  npm run db:seed   (or automatically via `prisma db seed`)
 */
import { questionService } from '../src/services';
import { dailyQuestionRepository } from '../src/repositories';
import { prisma } from '../src/database';
import { DAILY_QUESTION_COUNT } from '../src/constants';
import { toUtcDateOnly, dateKey } from '../src/utils/date';
import { logger } from '../src/utils/logger';

async function main(): Promise<void> {
  questionService.load();
  logger.info(`Question bank loaded: ${questionService.size} questions.`);

  const today = toUtcDateOnly();
  const exists = await dailyQuestionRepository.existsForDate(today);

  if (exists) {
    logger.info(`Daily questions already set for ${dateKey(today)}. Nothing to do.`);
    return;
  }

  const ids = questionService.pickRandomIds(DAILY_QUESTION_COUNT);
  await dailyQuestionRepository.setForDate(today, ids);
  logger.info(`Seeded daily questions [${ids.join(', ')}] for ${dateKey(today)}.`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
    process.exit(0);
  })
  .catch(async (err) => {
    logger.error('Seed failed.', err);
    await prisma.$disconnect();
    process.exit(1);
  });
